version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ntuee_artfest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ntuee_artfest
    ports:
      - "5432:5432"
volumes:
  postgres_data:
